sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - clang
  - gcc
script: "./.travis/build"
matrix:
  allow_failures:
    - compiler: clang
